import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { RouterTestingHarness } from '@angular/router/testing';
import { routes } from './app.routes';

const revision = {slug:'blueberry-v60-v2', revision:2, steps:[{atSeconds:0,waterGrams:60,action:'Bloom'}], equipment:{brewer:'V60',filter:'paper',grinder:'hand grinder'},grind:{clicks:20},temperatureC:93,coffeeGrams:20,waterGrams:300,commentary:'Sweeter finish'};
const recipe = {recipe:{slug:'blueberry-v60',name:'Blueberry V60'},currentRevision:revision,revisions:[revision,{...revision,slug:'blueberry-v60-v1',revision:1,grind:{clicks:21}}],notes:[],queries:[]};
const coffee = {batch:{slug:'ethiopia-blueberry-bloom',name:'Ethiopia Blueberry Bloom'},lot:{slug:'lot-1',name:'Ethiopia lot'},roaster:{slug:'roaster-1',name:'Community roaster'},vendor:{slug:'vendor-1',name:'Coffee vendor'},roastProfile:{slug:'profile-1',phases:[{name:'drying',seconds:240}]},brews:[{brew:{slug:'blueberry-bloom-v60',name:'Blueberry Bloom V60'},brewer:{slug:'priya-nair',name:'Priya Nair'},recipe:recipe.recipe,revision,reactions:[{person:{slug:'maya-chen',name:'Maya Chen'},kind:'LOVED',reaction:{comment:'Blueberry'}}]}],notes:[],queries:[]};
const privateNote = {slug:'private-note',body:'Remember the blueberry cup',visibility:'private',ownerSlug:'maya-chen',subjectType:'Brew',subjectSlug:'blueberry-bloom-v60'};

describe('Recipe documents and provenance', () => {
 let http: HttpTestingController;
 beforeEach(() => {TestBed.configureTestingModule({providers:[provideRouter(routes),provideHttpClient(),provideHttpClientTesting()]});http=TestBed.inject(HttpTestingController);});
 afterEach(() => {try {http.verify({ignoreCancelled:true});} finally {TestBed.resetTestingModule();}});
 const button = (h: RouterTestingHarness, text:string) => Array.from(h.routeNativeElement!.querySelectorAll('button')).find(b => b.textContent?.trim() === text)!;
 const field = (h:RouterTestingHarness, label:string) => Array.from(h.routeNativeElement!.querySelectorAll('label')).find(l=>l.firstChild?.textContent?.trim() === label)!.querySelector('input,textarea,select') as HTMLInputElement;
 const set = (element:HTMLInputElement, value:string) => {element.value=value;element.dispatchEvent(new Event('input'));element.dispatchEvent(new Event('change'));};
 const openMemory = async (h:RouterTestingHarness) => {h.routeNativeElement!.querySelector<HTMLButtonElement>('button[aria-controls="memory-panel"]')!.click();await h.fixture.whenStable();};
 async function load(mode='recipes') {const h=await RouterTestingHarness.create(mode==='recipes'?'/demo/recipes/blueberry-v60':'/demo/coffee/ethiopia-blueberry-bloom');http.expectOne(mode==='recipes'?'/api/demo/recipes/blueberry-v60?persona=maya-chen':'/api/demo/coffee/ethiopia-blueberry-bloom?persona=maya-chen').flush(mode==='recipes'?recipe:coffee);await h.fixture.whenStable();return h;}
 it('publishes structured fields against the loaded revision and compares immutable history', async()=>{
   const h=await load(); expect(h.routeNativeElement!.textContent).toContain('Why one database?');expect(h.routeNativeElement!.textContent).toContain('outbox or synchronization pipeline');expect(h.routeNativeElement!.textContent).toContain('21 → 20');set(field(h,'Grind clicks'),'18');button(h,'Publish revision').click();const req=http.expectOne('/api/demo/recipes/blueberry-v60/revisions');expect(req.request.body.expectedRevision).toBe(2);expect(req.request.body.revision.grind.clicks).toBe(18);expect(req.request.body.revision.steps[0].action).toBe('Bloom');req.flush({...recipe,currentRevision:{...revision,slug:'blueberry-v60-v3',revision:3,grind:{clicks:18}},revisions:[{...revision,slug:'blueberry-v60-v3',revision:3,grind:{clicks:18}},...recipe.revisions]});await h.fixture.whenStable();expect(h.routeNativeElement!.textContent).toContain('Revision 3 published');expect(h.routeNativeElement!.textContent).toContain('20 → 18');
 });
 it('retains the draft after a revision conflict and allows retry',async()=>{const h=await load();set(field(h,'Revision commentary'),'Keep my draft');button(h,'Publish revision').click();http.expectOne('/api/demo/recipes/blueberry-v60/revisions').flush({message:'Recipe changed; reload before publishing.'},{status:409,statusText:'Conflict'});await h.fixture.whenStable();expect(h.routeNativeElement!.querySelector('[role="alert"]')!.textContent).toContain('Recipe changed');expect(field(h,'Revision commentary').value).toBe('Keep my draft');expect(button(h,'Publish revision').disabled).toBe(false);});
 it('creates a recipe then reconstructs its deep link',async()=>{const h=await load();button(h,'New recipe').click();await h.fixture.whenStable();button(h,'Create recipe').click();const req=http.expectOne('/api/demo/recipes');expect(req.request.body.slug).toBe('story-recipe');const created={...recipe,recipe:{slug:'story-recipe',name:'Story pour-over'},currentRevision:{...revision,slug:'story-recipe-v1',revision:1},revisions:[]};req.flush(created);await h.fixture.whenStable();http.expectOne('/api/demo/recipes/story-recipe?persona=maya-chen').flush(created);await h.fixture.whenStable();expect(h.routeNativeElement!.textContent).toContain('Story pour-over');});
 it('selects connected documents, including the historical brew revision and reaction',async()=>{const h=await load('coffee');const lines=h.routeNativeElement!.querySelectorAll('svg line');expect(lines.length).toBeGreaterThan(5);expect(lines[0].getAttribute('marker-end')).toBe('url(#arrow)');expect(lines[0].getAttribute('x2')).not.toBe('110');expect(lines[0].getAttribute('y2')).not.toBe('60');const nodes=()=>Array.from(h.routeNativeElement!.querySelectorAll<HTMLButtonElement>('.graph-node'));nodes().find(n=>n.textContent!.includes('Pinned revision 2'))!.click();await h.fixture.whenStable();expect(h.routeNativeElement!.querySelector('.node-detail')!.textContent).toContain('blueberry-v60-v2');nodes().find(n=>n.textContent!.includes('LOVED'))!.click();await h.fixture.whenStable();expect(h.routeNativeElement!.querySelector('.node-detail')!.textContent).toContain('Blueberry');});
 it('keeps the same note subject while persona switching and cancels a stale private read',async()=>{const h=await load('coffee');await openMemory(h);set(field(h,'About'),'Brew');set(field(h,'Subject slug'),'blueberry-bloom-v60');button(h,'Load subject notes').click();const stale=http.expectOne('/api/demo/notes?persona=maya-chen&subjectType=Brew&subjectSlug=blueberry-bloom-v60');set(field(h,'Note'),'Unshared private draft');set(field(h,'Demo persona'),'priya-nair');await h.fixture.whenStable();expect(stale.cancelled).toBe(true);http.expectOne('/api/demo/coffee/ethiopia-blueberry-bloom?persona=priya-nair').flush(coffee);http.expectOne('/api/demo/notes?persona=priya-nair&subjectType=Brew&subjectSlug=blueberry-bloom-v60').flush({notes:[]});await h.fixture.whenStable();expect(field(h,'Subject slug').value).toBe('blueberry-bloom-v60');expect(field(h,'Note').value).toBe('');expect(h.routeNativeElement!.textContent).not.toContain(privateNote.body);set(field(h,'Demo persona'),'maya-chen');await h.fixture.whenStable();http.expectOne('/api/demo/coffee/ethiopia-blueberry-bloom?persona=maya-chen').flush(coffee);http.expectOne('/api/demo/notes?persona=maya-chen&subjectType=Brew&subjectSlug=blueberry-bloom-v60').flush({notes:[privateNote]});await h.fixture.whenStable();expect(h.routeNativeElement!.textContent).toContain(privateNote.body);});
 it('ignores a pending publication response after navigation changes the persona',async()=>{const h=await load();button(h,'Publish revision').click();const pending=http.expectOne('/api/demo/recipes/blueberry-v60/revisions');await h.navigateByUrl('/demo/recipes/blueberry-v60?persona=priya-nair');http.expectOne('/api/demo/recipes/blueberry-v60?persona=priya-nair').flush(recipe);await h.fixture.whenStable();set(field(h,'Revision commentary'),'Priya new draft');pending.flush({...recipe,notes:[privateNote],currentRevision:{...revision,revision:3}});await h.fixture.whenStable();expect(h.routeNativeElement!.textContent).not.toContain(privateNote.body);expect(h.routeNativeElement!.textContent).not.toContain('Revision 3 published');expect(field(h,'Revision commentary').value).toBe('Priya new draft');expect(button(h,'Publish revision').disabled).toBe(false);});
 it('ignores an old note-save response without clearing the new persona draft',async()=>{const h=await load();await openMemory(h);set(field(h,'Note'),'Maya note');await h.fixture.whenStable();button(h,'Save note').click();const pending=http.expectOne('/api/demo/notes');await h.navigateByUrl('/demo/recipes/blueberry-v60?persona=priya-nair');http.expectOne('/api/demo/recipes/blueberry-v60?persona=priya-nair').flush(recipe);await h.fixture.whenStable();set(field(h,'Note'),'Priya draft');pending.flush({notes:[privateNote]});await h.fixture.whenStable();expect(field(h,'Note').value).toBe('Priya draft');expect(h.routeNativeElement!.textContent).not.toContain('Note saved.');expect(h.routeNativeElement!.textContent).not.toContain(privateNote.body);http.expectNone(req=>req.method==='GET' && req.url==='/api/demo/notes');button(h,'Save note').click();const nextSave=http.expectOne('/api/demo/notes');expect(nextSave.request.body.slug).not.toBe(pending.request.body.slug);expect(nextSave.request.body.personSlug).toBe('priya-nair');nextSave.flush({detail:'Test failure'},{status:503,statusText:'Unavailable'});});
 it('saves a private note, reuses its retry key, and renders literal text',async()=>{const h=await load();await openMemory(h);set(field(h,'Note'),'<b>Private reminder</b>');await h.fixture.whenStable();button(h,'Save note').click();const first=http.expectOne('/api/demo/notes');const key=first.request.body.slug;expect(first.request.body.visibility).toBe('private');first.flush({detail:'Retry'},{status:503,statusText:'Unavailable'});await h.fixture.whenStable();button(h,'Save note').click();const second=http.expectOne('/api/demo/notes');expect(second.request.body.slug).toBe(key);second.flush({});http.expectOne('/api/demo/notes?persona=maya-chen&subjectType=Recipe&subjectSlug=blueberry-v60').flush({notes:[{...privateNote,body:'<b>Private reminder</b>'}]});await h.fixture.whenStable();expect(h.routeNativeElement!.querySelector('.note-body')!.textContent).toBe('<b>Private reminder</b>');expect(h.routeNativeElement!.querySelector('.note-body b')).toBeNull();});
});
